# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PyTorch Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'LibTorch'

  # Pods for PyTorch Demo

end
